- name: Ansible | add ansible repository
  apt_repository: repo='ppa:rquillo/ansible'
- name: Ansible | Install ansible via apt
  apt: pkg=ansible state=present update_cache=yes
- name: Ansible | Install git via apt
  apt: pkg=git state=present
- name: Ansible | clone ansible playbooks
  git: repo=https://github.com/Mic92/ansible-mongodb.git dest=/root/ansible
